# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "v6" ]
  pull_request:
    branches: [ "v6" ]

jobs:
  build-ios:

    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: xcodebuild -scheme AudioKit -destination "platform=iOS Simulator,name=iPhone 14" 
    - name: Run tests
      run: xcodebuild -scheme AudioKit -destination "platform=iOS Simulator,name=iPhone 14" test
