name: Tests

on:
  workflow_dispatch:
  push:
    branches: [main, v6]
  pull_request:
    branches: [main]

jobs:
  swift_test:
    name: Test
    uses: AudioKit/ci/.github/workflows/swift_test.yml@main
    with:
      scheme: AudioKit
      platforms: iOS macOS
      swift-versions: 5.7

  # Send notification to Discord on failure.
  send_notification:
    name: Send Notification
    uses: AudioKit/ci/.github/workflows/send_notification.yml@main
    needs: [swift_test]
    if: ${{ failure() && github.ref == 'refs/heads/main' }}
    secrets: inherit
